# Test profile configuration - uses H2 in-memory database for testing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=Wiley@1234

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

#azure open AI configuration
azure.openai.endpoint=https://apex-innovation-poc-july-2025.openai.azure.com/
azure.openai.api-key=41hlWPxZaJuHnXX556pIwXOEmrmObOebV6jTGr2wQmjFY9XxMCu7JQQJ99BGACYeBjFXJ3w3AAABACOGF1kM
azure.openai.assistant-id=asst_QQOwYP8N3pGBwwD4TWZxF7uY
